# Generated by Django 6.0.2 on 2026-02-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='mentorearning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mentor Earning', 'verbose_name_plural': 'Mentor Earnings'},
        ),
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payout', 'verbose_name_plural': 'Payouts'},
        ),
    ]
