# Generated by Django 6.0.2 on 2026-02-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentsettings_application_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproof',
            name='proof_image',
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Proof Document'),
        ),
    ]
