# Generated by Django 6.0.2 on 2026-02-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_paymentproof_proof_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentproof',
            old_name='proof_file',
            new_name='proof_image',
        ),
    ]
