# Generated by Django 6.0.2 on 2026-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_proof_file_paymentproof_proof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_code',
            field=models.CharField(blank=True, default='', help_text='USSD code or merchant code e.g. *182*8*1*123456#', max_length=200, verbose_name='Payment Code'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_instructions',
            field=models.TextField(blank=True, default='', help_text='Instructions shown to students during subscription', verbose_name='Payment Instructions'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='payment_number',
            field=models.CharField(blank=True, default='', help_text='MoMo number or bank account number students pay to', max_length=100, verbose_name='Payment Number'),
        ),
    ]
