# Generated by Django 6.0.2 on 2026-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentsettings_payment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='account_name',
            field=models.CharField(default='MentorConnect Ltd', max_length=100, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='account_number',
            field=models.CharField(default='00040-0065432-12', max_length=100, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='bank_name',
            field=models.CharField(default='Bank of Kigali (BK)', max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='mobile_money_number',
            field=models.CharField(default='*182*8*1*556644#', max_length=100, verbose_name='Mobile Money Code'),
        ),
    ]
