# Generated by Django 6.0.2 on 2026-02-06 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icon class name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell students about yourself and your experience', max_length=2000)),
                ('headline', models.CharField(blank=True, help_text='e.g., Senior Software Engineer at Google', max_length=200)),
                ('expertise', models.CharField(help_text='Your main area of expertise', max_length=200)),
                ('skills', models.TextField(help_text='Comma-separated list of skills you can teach')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Company/Organization')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job Title')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Mentoring')),
                ('max_mentees', models.PositiveIntegerField(default=5, verbose_name='Maximum Number of Mentees')),
                ('session_duration', models.PositiveIntegerField(default=60, help_text='Default session duration in minutes', verbose_name='Session Duration')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Leave 0 for free mentoring', max_digits=10, verbose_name='Hourly Rate')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Profile',
                'verbose_name_plural': 'Mentor Profiles',
                'ordering': ['-is_featured', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=1000)),
                ('headline', models.CharField(blank=True, help_text='e.g., Computer Science Student at University of Rwanda', max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='School/University')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='Field of Study')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected Graduation Year')),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills (e.g., Python, Data Analysis, Leadership)')),
                ('interests', models.TextField(blank=True, help_text='What topics are you interested in learning about?')),
                ('goals', models.TextField(blank=True, help_text='What are your career goals?')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV/Resume')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio')),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'followed')},
            },
        ),
    ]
