# Generated by Django 6.0.2 on 2026-02-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
