# Generated by Django 6.0.2 on 2026-02-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_mentorprofile_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='accepts_in_person',
            field=models.BooleanField(default=True, help_text='Allow students to shadow you at your workplace', verbose_name='Accepts In-Person Shadowing'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='accepts_virtual',
            field=models.BooleanField(default=False, help_text='Offer virtual mentoring sessions', verbose_name='Accepts Virtual Sessions'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='city',
            field=models.CharField(blank=True, help_text='e.g., Kigali, Nairobi, Lagos', max_length=100, verbose_name='City/Region'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='country',
            field=models.CharField(blank=True, default='Rwanda', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='diploma',
            field=models.CharField(blank=True, help_text='e.g., Master of Medicine, Bachelor of Engineering', max_length=200, verbose_name='Diploma/Degree'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='educational_institution',
            field=models.CharField(blank=True, help_text='e.g., University of Rwanda, MIT', max_length=200, verbose_name='Educational Institution'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='max_internship_days',
            field=models.PositiveIntegerField(default=5, help_text='Maximum days for observation internship (1-5)', verbose_name='Maximum Internship Days'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='min_internship_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum days for observation internship (1-5)', verbose_name='Minimum Internship Days'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='workplace_address',
            field=models.TextField(blank=True, help_text='Where students will shadow you', verbose_name='Workplace Address'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Job Title/Profession'),
        ),
    ]
