# Generated by Django 6.0.2 on 2026-02-14 16:24

import applications.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('mentorship', '0003_alter_mentoravailability_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('status_change', 'Status Change'), ('payment_verified', 'Payment Verified'), ('payment_submitted', 'Payment Submitted'), ('note', 'Note')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('previous_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_minor', models.BooleanField(db_index=True, default=False)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('parent_contact', models.CharField(blank=True, max_length=200)),
                ('parent_consent_required', models.BooleanField(default=False)),
                ('parent_notified', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('tracking_code', models.CharField(db_index=True, default='', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_finance', 'Pending Finance'), ('finance_rejected', 'Finance Rejected'), ('pending_review', 'Pending Review'), ('review_rejected', 'Review Rejected'), ('approved', 'Approved'), ('enrolled', 'Enrolled')], db_index=True, default='draft', max_length=30)),
                ('locked', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/cvs/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('mentorship_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='mentorship.mentorshiprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_code', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$')])),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payments/receipts/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applications.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tracking_code'], name='application_trackin_0b2239_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['email'], name='application_email_c09a19_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
    ]
