# Generated by Django 6.0.2 on 2026-02-14 19:21

import applications.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationdraft'),
        ('mentorship', '0005_extend_application_wizard_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationWizardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('step_data', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Wizard Session',
                'verbose_name_plural': 'Application Wizard Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Application Activity Log', 'verbose_name_plural': 'Application Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='applicationdraft',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Application Draft', 'verbose_name_plural': 'Application Drafts'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_status_1508e0_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_trackin_0b2239_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_email_c09a19_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='application_created_c6d08d_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationdraft',
            name='application_session_eeebe4_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicationdraft',
            name='application_mentor__baa7a9_idx',
        ),
        migrations.AddField(
            model_name='application',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Calculated from DOB', null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='application',
            name='career_goals',
            field=models.TextField(blank=True, verbose_name='Career Goals'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_step',
            field=models.PositiveIntegerField(default=1, help_text='1-5', verbose_name='Wizard Step'),
        ),
        migrations.AddField(
            model_name='application',
            name='expectations',
            field=models.TextField(blank=True, verbose_name='Expectations from Mentor'),
        ),
        migrations.AddField(
            model_name='application',
            name='motivation',
            field=models.TextField(blank=True, verbose_name='Motivation for Mentorship'),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_consent_given',
            field=models.BooleanField(default=False, verbose_name='Parent Consent Given'),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Parent/Guardian Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Parent/Guardian Phone'),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Relationship to Applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program of Study'),
        ),
        migrations.AddField(
            model_name='application',
            name='school',
            field=models.CharField(blank=True, max_length=200, verbose_name='School/University'),
        ),
        migrations.AddField(
            model_name='application',
            name='selected_availability_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='mentorship.mentoravailability'),
        ),
        migrations.AddField(
            model_name='application',
            name='selected_mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='applications/cvs/', verbose_name='CV/Resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='application',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department/Field'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_minor',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Minor (under 18)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='Locked'),
        ),
        migrations.AlterField(
            model_name='application',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent_consent_required',
            field=models.BooleanField(default=False, verbose_name='Parent Consent Required'),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parent/Guardian Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent_notified',
            field=models.BooleanField(default=False, verbose_name='Parent Notified'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tracking_code',
            field=models.CharField(db_index=True, default=applications.models.generate_tracking_code, max_length=32, unique=True, verbose_name='Tracking Code'),
        ),
        migrations.AlterField(
            model_name='applicationdraft',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='Receipt'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'Only letters, numbers and hyphens allowed.')], verbose_name='Transaction Code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='applicationwizardsession',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wizard_session', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationwizardsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wizard_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='application',
            name='parent_contact',
        ),
    ]
