# Generated by Django 6.0.2 on 2026-02-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_extend_application_wizard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parent/Guardian Contact'),
        ),
    ]
