# Generated by Django 6.0.2 on 2026-02-06 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MentorConnect', max_length=100)),
                ('site_tagline', models.CharField(default='Connect with mentors, grow your future', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(default='contact@mentorconnect.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(default='© 2026 MentorConnect. All rights reserved.')),
                ('enable_chat', models.BooleanField(default=True)),
                ('enable_feed', models.BooleanField(default=True)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_text_to_speech', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='We are currently under maintenance. Please check back later.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., Student, Mentor, Alumni', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Theme', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#4F46E5', help_text='Main brand color (e.g., #4F46E5)', max_length=7)),
                ('primary_hover', models.CharField(default='#4338CA', help_text='Primary hover state', max_length=7)),
                ('primary_light', models.CharField(default='#EEF2FF', help_text='Light variant of primary', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', help_text='Secondary accent color', max_length=7)),
                ('secondary_hover', models.CharField(default='#059669', max_length=7)),
                ('background_color', models.CharField(default='#F9FAFB', help_text='Main background', max_length=7)),
                ('surface_color', models.CharField(default='#FFFFFF', help_text='Card/surface background', max_length=7)),
                ('text_primary', models.CharField(default='#111827', help_text='Primary text color', max_length=7)),
                ('text_secondary', models.CharField(default='#6B7280', help_text='Secondary text color', max_length=7)),
                ('text_muted', models.CharField(default='#9CA3AF', help_text='Muted text color', max_length=7)),
                ('success_color', models.CharField(default='#10B981', max_length=7)),
                ('warning_color', models.CharField(default='#F59E0B', max_length=7)),
                ('error_color', models.CharField(default='#EF4444', max_length=7)),
                ('info_color', models.CharField(default='#3B82F6', max_length=7)),
                ('navbar_bg', models.CharField(default='#FFFFFF', max_length=7)),
                ('navbar_text', models.CharField(default='#374151', max_length=7)),
                ('footer_bg', models.CharField(default='#1F2937', max_length=7)),
                ('footer_text', models.CharField(default='#F9FAFB', max_length=7)),
                ('button_radius', models.CharField(default='0.5rem', help_text='Border radius for buttons', max_length=20)),
                ('card_radius', models.CharField(default='1rem', help_text='Border radius for cards', max_length=20)),
                ('shadow_sm', models.CharField(default='0 1px 2px 0 rgba(0, 0, 0, 0.05)', max_length=100)),
                ('shadow_md', models.CharField(default='0 4px 6px -1px rgba(0, 0, 0, 0.1)', max_length=100)),
                ('shadow_lg', models.CharField(default='0 10px 15px -3px rgba(0, 0, 0, 0.1)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('profile_update', 'Profile Update'), ('mentor_request', 'Mentor Request'), ('session_book', 'Session Booked'), ('session_complete', 'Session Completed'), ('post_create', 'Post Created'), ('message_send', 'Message Sent'), ('admin_action', 'Admin Action'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this text', max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda')], max_length=5)),
                ('text', models.TextField()),
                ('context', models.CharField(blank=True, help_text='Where this translation is used', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key', 'language'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
