# Generated by Django 6.0.2 on 2026-02-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('profile_update', 'Profile Update'), ('mentor_request', 'Mentor Request'), ('session_book', 'Session Booked'), ('session_complete', 'Session Completed'), ('post_create', 'Post Created'), ('message_send', 'Message Sent'), ('admin_action', 'Admin Action'), ('mentor_facilitator_action', 'Mentor Facilitator Action'), ('finance_officer_action', 'Finance Officer Action'), ('other', 'Other')], max_length=50),
        ),
    ]
