# Generated by Django 6.0.2 on 2026-02-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0004_session_session_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='availability',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='availability',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location Name'),
        ),
        migrations.AddField(
            model_name='availability',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
