# Generated by assistant: add scheduling fields for datetime-range availability and session linking
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0005_availability_address_availability_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Start datetime of availability', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='end',
            field=models.DateTimeField(blank=True, help_text='End datetime of availability', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_sessions', to='sessions_app.availability'),
        ),
        migrations.AddField(
            model_name='session',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
