# Generated by assistant: add session_type to Availability
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0006_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='session_type',
            field=models.CharField(choices=[('online', 'online'), ('physical', 'physical')], default='online', max_length=20),
        ),
    ]
