# Generated by Django 6.0.2 on 2026-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_app', '0008_alter_availability_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('approved', 'approved'), ('rejected', 'rejected'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
