# Generated by Django 6.0.2 on 2026-02-06 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshiprequest',
            name='meeting_link',
            field=models.URLField(blank=True, verbose_name='Meeting Link'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='meeting_notes',
            field=models.TextField(blank=True, verbose_name='Meeting Notes'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Awaiting Schedule'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('title', models.CharField(max_length=200, verbose_name='What you will be doing')),
                ('description', models.TextField(blank=True, verbose_name='Additional details')),
                ('is_booked', models.BooleanField(default=False)),
                ('max_bookings', models.PositiveIntegerField(default=1, verbose_name='Max number of students')),
                ('current_bookings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Availability',
                'verbose_name_plural': 'Mentor Availabilities',
                'ordering': ['date', 'start_time'],
                'unique_together': {('mentor', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='availability_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='mentorship.mentoravailability'),
        ),
    ]
