# Generated by Django 6.0.2 on 2026-02-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_mentorshiprequest_meeting_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentoravailability',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Observation Slot', 'verbose_name_plural': 'Observation Slots'},
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='location_address',
            field=models.TextField(blank=True, help_text='Where the observation internship will take place', verbose_name='Location/Address'),
        ),
        migrations.AddField(
            model_name='mentoravailability',
            name='location_type',
            field=models.CharField(choices=[('in_person', 'In-Person (At Workplace)'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid (Both)')], default='in_person', max_length=20, verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='current_education',
            field=models.CharField(blank=True, help_text='e.g., Final year secondary school, 2nd year Bachelor', max_length=200, verbose_name='Current Education Level'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='field_of_interest',
            field=models.CharField(blank=True, help_text='What field/profession are you considering?', max_length=200, verbose_name='Field of Interest'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='nda_agreed',
            field=models.BooleanField(default=False, help_text='Student has agreed to Non-Disclosure Agreement', verbose_name='NDA Agreement'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='nda_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='request_type',
            field=models.CharField(choices=[('observation', 'Observation Internship (In-Person)'), ('virtual', 'Virtual Mentoring'), ('hybrid', 'Hybrid (Both)')], default='observation', max_length=20, verbose_name='Type of Mentorship'),
        ),
        migrations.AddField(
            model_name='mentorshiprequest',
            name='requested_days',
            field=models.PositiveIntegerField(default=1, help_text='How many days (1-5) would you like to shadow?', verbose_name='Number of Days Requested'),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='mentoravailability',
            name='description',
            field=models.TextField(blank=True, verbose_name='Additional details about the observation'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='goals',
            field=models.TextField(blank=True, verbose_name='What do you hope to learn?'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='message',
            field=models.TextField(verbose_name='Why do you want to shadow this professional?'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Profession/Role of Interest'),
        ),
    ]
