# Generated by Django 6.0.2 on 2026-02-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_mentorfacilitator_dispute_sessionreport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dispute', 'verbose_name_plural': 'Disputes'},
        ),
        migrations.AlterModelOptions(
            name='mentorfacilitator',
            options={'verbose_name': 'Mentor Facilitator', 'verbose_name_plural': 'Mentor Facilitators'},
        ),
        migrations.AlterModelOptions(
            name='mentorfacilitatorassignment',
            options={'verbose_name': 'Mentor Facilitator Assignment', 'verbose_name_plural': 'Mentor Facilitator Assignments'},
        ),
        migrations.AlterModelOptions(
            name='sessionreport',
            options={'ordering': ['-session_date', '-session_time'], 'verbose_name': 'Session Report', 'verbose_name_plural': 'Session Reports'},
        ),
        migrations.AlterField(
            model_name='dispute',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='session_date',
            field=models.DateField(verbose_name='Session Date'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='session_time',
            field=models.TimeField(verbose_name='Session Time'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='summary_notes',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
    ]
