# Generated by Django 6.0.2 on 2026-02-14 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_extend_application_wizard_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_score', models.FloatField(default=0.0, help_text='Overall success score (0-10) based on multiple factors', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('engagement_level', models.FloatField(default=0.0, help_text='Engagement level percentage based on session attendance and interactions', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('goal_completion_rate', models.FloatField(default=0.0, help_text='Percentage of mentorship goals completed', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('session_attendance_rate', models.FloatField(default=0.0, help_text='Percentage of sessions attended', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('time_to_match', models.PositiveIntegerField(blank=True, help_text='Time in hours from request to approval', null=True)),
                ('time_to_schedule', models.PositiveIntegerField(blank=True, help_text='Time in hours from approval to scheduling', null=True)),
                ('time_to_completion', models.PositiveIntegerField(blank=True, help_text='Time in hours from start to completion', null=True)),
                ('total_duration_hours', models.PositiveIntegerField(default=0, help_text='Total mentorship duration in hours')),
                ('student_satisfaction', models.FloatField(default=0.0, help_text='Student satisfaction score (0-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('mentor_satisfaction', models.FloatField(default=0.0, help_text='Mentor satisfaction score (0-5)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('skill_improvement_score', models.FloatField(default=0.0, help_text='Measured skill improvement (0-10)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('at_risk_score', models.FloatField(default=0.0, help_text='Risk score indicating potential issues (0-10)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('intervention_needed', models.BooleanField(default=False)),
                ('last_intervention_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mentorship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='mentorship.mentorshiprequest')),
            ],
            options={
                'verbose_name': 'Mentorship Analytics',
                'verbose_name_plural': 'Mentorship Analytics',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
