# Generated by Django 6.0.2 on 2026-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('mentor_facilitator', 'Mentor Facilitator'), ('finance_manager', 'Finance Manager')], default='student', max_length=20, verbose_name='Role'),
        ),
    ]
