# Generated by Django 6.0.2 on 2026-02-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('mentor_facilitator', 'Mentor Facilitator'), ('finance_manager', 'Finance Officer'), ('mentorship_department', 'Mentorship Department')], default='student', max_length=25, verbose_name='Role'),
        ),
    ]
